In [ ]:
from google.colab import files
uploaded = files.upload()

Saving bbc_news.csv to bbc_news.csv

In [ ]:
import spacy
import pandas as pd

In [ ]:
data = pd.read_csv("bbc_news.csv")
data.head(5)

,Unnamed: 0,index,title,pubDate,guid,link,description
0,0,6684,Can I refuse to work?,"Wed, 10 Aug 2022 15:46:18 GMT",https://www.bbc.co.uk/news/business-62147992,https://www.bbc.co.uk/news/business-62147992?a...,With much of the UK enduring another period of...
1,1,9267,'Liz Truss the Brief?' World reacts to UK poli...,"Mon, 17 Oct 2022 11:35:12 GMT",https://www.bbc.co.uk/news/world-63285480,https://www.bbc.co.uk/news/world-63285480?at_m...,The UK's political chaos has been watched arou...
2,2,7387,Rationing energy is nothing new for off-grid c...,"Wed, 31 Aug 2022 05:20:18 GMT",https://www.bbc.co.uk/news/uk-scotland-highlan...,https://www.bbc.co.uk/news/uk-scotland-highlan...,Scoraig in the north west Highlands has long h...
3,3,767,The hunt for superyachts of sanctioned Russian...,"Tue, 22 Mar 2022 14:37:01 GMT",https://www.bbc.co.uk/news/60739336,https://www.bbc.co.uk/news/60739336?at_medium=...,"Wealthy Russians sanctioned by the US, EU and ..."
4,4,3712,Platinum Jubilee: 70 years of the Queen in 70 ...,"Wed, 01 Jun 2022 23:17:33 GMT",https://www.bbc.co.uk/news/uk-61660128,https://www.bbc.co.uk/news/uk-61660128?at_medi...,A quick look back at the Queen's 70 years on t...

In [ ]:
nlp = spacy.load("en_core_web_sm")
dataTitle = pd.DataFrame(data['title'])
pos_doc_title = dataTitle.apply(lambda x: [nlp(text) for text in x])
pos_doc_title

                                                 title
0                        (Can, I, refuse, to, work, ?)
1    (', Liz, Truss, the, Brief, ?, ', World, react...
2    (Rationing, energy, is, nothing, new, for, off...
3    (The, hunt, for, superyachts, of, sanctioned, ...
4    (Platinum, Jubilee, :, 70, years, of, the, Que...
..                                                 ...
995  (Dominic, Raab, :, Third, senior, civil, serva...
996         (Highlights, :, Radacanu, beats, Uytvanck)
997  (In, pictures, :, Mountain, bikers, descend, s...
998  (Companies, must, help, cut, living, costs, ,,...
999  (Beware, online, car, sale, scams, ,, consumer...

[1000 rows x 1 columns]

In [ ]:
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import re
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
#removal of stop words:
dataTitle['title_lower'] = dataTitle['title'].str.lower()
en_stopwords = stopwords.words('english')
dataTitle['title_nostop'] = dataTitle['title_lower'].apply(lambda x : ' '.join([word for word in x if word not in en_stopwords]))
dataTitle['title_nostop']

0                          c n     r e f u e     w r k ?
1      ' l z   r u   h e   b r e f ? '   w r l   r e ...
2      r n n g   e n e r g     n h n g   n e w   f r ...
3      h e   h u n   f r   u p e r c h   f   n c n e ...
4      p l n u   j u b l e e :   7 0   e r   f   h e ...
                             ...
995    n c   r b :   h r   e n r   c v l   e r v n   ...
996            h g h l g h :   r c n u   b e   u v n c k
997    n   p c u r e :   u n n   b k e r   e c e n   ...
998    c p n e   u   h e l p   c u   l v n g   c ,   ...
999    b e w r e   n l n e   c r   l e   c ,   c n u ...
Name: title_nostop, Length: 1000, dtype: object

In [ ]:
#removal of punctuations:
dataTitle['title_nopunct'] =dataTitle.apply(lambda x : re.sub(r"([^\w\s])","",x['title_nostop']),axis=1)
dataTitle['title_nopunct']

0                                   Can I refuse to work
1      Liz Truss the Brief World reacts to UK politic...
2      Rationing energy is nothing new for offgrid co...
3      The hunt for superyachts of sanctioned Russian...
4      Platinum Jubilee 70 years of the Queen in 70 s...
                             ...
995    Dominic Raab Third senior civil servant gives ...
996                   Highlights Radacanu beats Uytvanck
997       In pictures Mountain bikers descend snowy peak
998    Companies must help cut living costs says new ...
999        Beware online car sale scams consumers warned
Name: title_nopunct, Length: 1000, dtype: object

In [ ]:
#tokenise the data Titles:

dataTitle['tokenised'] = dataTitle.apply(lambda x : word_tokenize(x['title_nopunct']),axis=1)
dataTitle['tokenised']

0                             [Can, I, refuse, to, work]
1      [Liz, Truss, the, Brief, World, reacts, to, UK...
2      [Rationing, energy, is, nothing, new, for, off...
3      [The, hunt, for, superyachts, of, sanctioned, ...
4      [Platinum, Jubilee, 70, years, of, the, Queen,...
                             ...
995    [Dominic, Raab, Third, senior, civil, servant,...
996              [Highlights, Radacanu, beats, Uytvanck]
997    [In, pictures, Mountain, bikers, descend, snow...
998    [Companies, must, help, cut, living, costs, sa...
999    [Beware, online, car, sale, scams, consumers, ...
Name: tokenised, Length: 1000, dtype: object

In [ ]:
nltk.download('wordnet')
wdlem = WordNetLemmatizer()
dataTitle['title_lemmatised'] = dataTitle['tokenised'].apply(lambda x : [wdlem.lemmatize(word) for word in x])
dataTitle['title_lemmatised']

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

0                             [Can, I, refuse, to, work]
1      [Liz, Truss, the, Brief, World, reacts, to, UK...
2      [Rationing, energy, is, nothing, new, for, off...
3      [The, hunt, for, superyachts, of, sanctioned, ...
4      [Platinum, Jubilee, 70, year, of, the, Queen, ...
                             ...
995    [Dominic, Raab, Third, senior, civil, servant,...
996               [Highlights, Radacanu, beat, Uytvanck]
997    [In, picture, Mountain, bikers, descend, snowy...
998    [Companies, must, help, cut, living, cost, say...
999    [Beware, online, car, sale, scam, consumer, wa...
Name: title_lemmatised, Length: 1000, dtype: object

In [ ]:
title_final = sum(dataTitle['title_lemmatised'],[])
unigrams = pd.DataFrame(nltk.ngrams(title_final,1))
unigrams.value_counts()

0
to         241
in         186
of         171
the        163
and        147
          ...
written      1
writes       1
wrap         1
wow          1
wound        1
Name: count, Length: 3892, dtype: int64