In [ ]:
import spacy
import pandas as pd

In [ ]:
nlp = spacy.load('en_core_web_sm')

In [ ]:
emma_ja = "Google was founded on September 4, 1998, by computer scientists Larry Page and Sergey Brin while they were PhD students at Stanford University in California. Together they own about 14% of its publicly listed shares and control 56% of its stockholder voting power through super-voting stock. The company went public via an initial public offering (IPO) in 2004. In 2015, Google was reorganized as a wholly owned subsidiary of Alphabet Inc. Google is Alphabet's largest subsidiary and is a holding company for Alphabet's internet properties and interests. Sundar Pichai was appointed CEO of Google on October 24, 2015, replacing Larry Page, who became the CEO of Alphabet. On December 3, 2019, Pichai also became the CEO of Alphabet."
print(emma_ja)

Google was founded on September 4, 1998, by computer scientists Larry Page and Sergey Brin while they were PhD students at Stanford University in California. Together they own about 14% of its publicly listed shares and control 56% of its stockholder voting power through super-voting stock. The company went public via an initial public offering (IPO) in 2004. In 2015, Google was reorganized as a wholly owned subsidiary of Alphabet Inc. Google is Alphabet's largest subsidiary and is a holding company for Alphabet's internet properties and interests. Sundar Pichai was appointed CEO of Google on October 24, 2015, replacing Larry Page, who became the CEO of Alphabet. On December 3, 2019, Pichai also became the CEO of Alphabet.

In [ ]:
spacy_doc = nlp(emma_ja)

In [ ]:
pos_df = pd.DataFrame(columns=['token','pos_tag'])
for token in  spacy_doc:
  pos_df = pd.concat([pos_df,pd.DataFrame.from_records([{'token':token.text,'pos_tag':token.pos_}])],ignore_index=True)

In [ ]:
pos_df.head()

       token pos_tag
0     Google   PROPN
1        was     AUX
2    founded    VERB
3         on     ADP
4  September   PROPN

In [ ]:
pos_df_counts = pos_df.groupby(['token','pos_tag']).size().reset_index(name='counts').sort_values(by='counts',ascending=False)
pos_df_counts.head(4)

       token pos_tag  counts
4          ,   PUNCT       8
6          .   PUNCT       6
63        of     ADP       6
16  Alphabet   PROPN       5

In [ ]:
pos_tag_counts = pos_df.groupby(['pos_tag']).size().reset_index(name='counts').sort_values(by='counts',ascending=False)
pos_tag_counts.head()

   pos_tag  counts
10   PROPN      28
6     NOUN      20
1      ADP      18
11   PUNCT      16
13    VERB      12

In [ ]:
common_nouns = pos_df[pos_df.pos_tag == 'NOUN'].groupby(['token']).size().reset_index(name='counts').sort_values(by='counts',ascending=False)
common_nouns.head()

         token  counts
0            %       2
3      company       2
15  subsidiary       2
2          PhD       1
1          CEO       1

NER using spacy

In [ ]:
from spacy import displacy
from spacy import tokenizer
import re

In [ ]:
google_text = "Google was founded on September 4, 1998, by computer scientists Larry Page and Sergey Brin while they were PhD students at Stanford University in California. Together they own about 14% of its publicly listed shares and control 56% of its stockholder voting power through super-voting stock. The company went public via an initial public offering (IPO) in 2004. In 2015, Google was reorganized as a wholly owned subsidiary of Alphabet Inc. Google is Alphabet's largest subsidiary and is a holding company for Alphabet's internet properties and interests. Sundar Pichai was appointed CEO of Google on October 24, 2015, replacing Larry Page, who became the CEO of Alphabet. On December 3, 2019, Pichai also became the CEO of Alphabet."
google_text

"Google was founded on September 4, 1998, by computer scientists Larry Page and Sergey Brin while they were PhD students at Stanford University in California. Together they own about 14% of its publicly listed shares and control 56% of its stockholder voting power through super-voting stock. The company went public via an initial public offering (IPO) in 2004. In 2015, Google was reorganized as a wholly owned subsidiary of Alphabet Inc. Google is Alphabet's largest subsidiary and is a holding company for Alphabet's internet properties and interests. Sundar Pichai was appointed CEO of Google on October 24, 2015, replacing Larry Page, who became the CEO of Alphabet. On December 3, 2019, Pichai also became the CEO of Alphabet."

In [ ]:
google_text_cleaned = re.sub(r'[^\w\s]','',google_text).lower()
print(google_text_cleaned)

google was founded on september 4 1998 by computer scientists larry page and sergey brin while they were phd students at stanford university in california together they own about 14 of its publicly listed shares and control 56 of its stockholder voting power through supervoting stock the company went public via an initial public offering ipo in 2004 in 2015 google was reorganized as a wholly owned subsidiary of alphabet inc google is alphabets largest subsidiary and is a holding company for alphabets internet properties and interests sundar pichai was appointed ceo of google on october 24 2015 replacing larry page who became the ceo of alphabet on december 3 2019 pichai also became the ceo of alphabet

In [ ]:
s_doc = nlp(google_text_cleaned)

In [ ]:
for word in s_doc.ents:
  print(word.text,word.label_)

google ORG
september 4 1998 DATE
stanford university ORG
california GPE
about 14 CARDINAL
56 CARDINAL
2004 DATE
2015 DATE
alphabet inc google ORG
google ORG
october 24 2015 DATE
larry PERSON
december 3 2019 DATE

In [ ]:
displacy.render(s_doc,style='ent',jupyter=True)

In [ ]:
displacy.render(s_doc,style='dep',jupyter=True)