In [ ]:
from google.colab import files
uploaded = files.upload()

Saving tripadvisor_hotel_reviews.csv to tripadvisor_hotel_reviews.csv

In [ ]:
import pandas as pd

In [ ]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer,WordNetLemmatizer
from nltk.corpus import stopwords
import re
import pandas as pd
import io

In [ ]:
data = pd.read_csv(io.BytesIO(uploaded['tripadvisor_hotel_reviews.csv']))

In [ ]:
data.sample(3)

                                               Review  Rating
97  terrible hotel approximately 2 weeks ago april...       1
2   nice rooms not 4* experience hotel monaco seat...       3
70  ace hotel, reasonably priced hotel great locat...       4

In [ ]:
data["Review"][92]

'quaint not rundown son decided celebrate graduation high school trip seattle, chose inn queen anne proximity experience music project space needle funky shops eateries nearby, hotel described quaint pictures hotel website nice gave shot.upon entering hotel greeted carpet lobby filthy torn, uh-oh thought not good sign, desk overbooked paid confirmed reservations late arrival 2 weeks prior room left 2 beds, took hurriedly left things room grab quick bite, returning getting bed noticed room no a/c windows not open son double bed clean twin hairy sheets closet, not talking old fashioned wall pull-out bed-this actually tiny twin bed stuffed closet, went kitchenette leftovers fridge fridge mold did not work, went desk complain told nothing sucked tried sleep, took sheets bed used sons blanket eventually closet got stuffy jumped sons bed fan, morning experienced plumbing issues toilet shower bugs bathroom, packing looked bed make sure got discovered possessions stayed did, housekeepers did not clean beds change sheets, canceled rest stay decided leave seattle drove anacortes stayed cap sante inn- palace compared night before.i wrote manager queen anne requesting refund, received letter saying refund not given gave coupon stay, use, word quaint queen anne uses advertising not rundown.my advice anybody staying check room white glove inspection make sure working order agree stay it.by way queen anne policy reserve room charge card immediately not refund 72 hours advance cancellation, ridiculous,  '

In [ ]:
data["review_lc"] = data["Review"].str.lower()
data.head()

,Review,Rating,review_lc
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso..."

In [ ]:
nltk.download('stopwords')
en_stopwords = stopwords.words("english")
en_stopwords.remove('not')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [ ]:
data['reviews_nostop'] = data['review_lc'].apply(lambda x: ' '.join([word for word in x.split() if word not in en_stopwords]))
data['reviews_nostop']

0      nice hotel expensive parking got good deal sta...
1      ok nothing special charge diamond member hilto...
2      nice rooms not 4* experience hotel monaco seat...
3      unique, great stay, wonderful time hotel monac...
4      great stay great stay, went seahawk game aweso...
                             ...
104    fairmont hotel singapore splendid, stayed fair...
105    great hotel stayed hotel night route perth chr...
106    great hotel centre stayed 5 nights room overlo...
107    great location great value great hotel husband...
108    lovely hotel great location stayed vacation to...
Name: reviews_nostop, Length: 109, dtype: object

In [ ]:
data['reviews_no_punct'] = data.apply(lambda x : re.sub(r"[*]",'star',x['reviews_nostop']),axis=1)

In [ ]:
data['processed'] = data.apply(lambda x : re.sub(r"([^\w\s])","",x['reviews_no_punct']),axis=1)
data['processed']

0      nice hotel expensive parking got good deal sta...
1      ok nothing special charge diamond member hilto...
2      nice rooms not 4star experience hotel monaco s...
3      unique great stay wonderful time hotel monaco ...
4      great stay great stay went seahawk game awesom...
                             ...
104    fairmont hotel singapore splendid stayed fairm...
105    great hotel stayed hotel night route perth chr...
106    great hotel centre stayed 5 nights room overlo...
107    great location great value great hotel husband...
108    lovely hotel great location stayed vacation to...
Name: processed, Length: 109, dtype: object

In [ ]:
nltk.download('punkt_tab')
data['tokenised'] = data.apply(lambda x : word_tokenize(x['processed']),axis=1)
data.head(3)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

,Review,Rating,review_lc,reviews_nostop,reviews_no_punct,processed,tokenised
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,"[nice, hotel, expensive, parking, got, good, d..."
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,"[ok, nothing, special, charge, diamond, member..."
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4star experience hotel monaco s...,nice rooms not 4star experience hotel monaco s...,"[nice, rooms, not, 4star, experience, hotel, m..."

In [ ]:
ps = PorterStemmer()
data['Stemmed'] = data['tokenised'].apply(lambda x : [ps.stem(word) for word in x])
data.head()

,Review,Rating,review_lc,reviews_nostop,reviews_no_punct,processed,tokenised,Stemmed
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,"[nice, hotel, expensive, parking, got, good, d...","[nice, hotel, expens, park, got, good, deal, s..."
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,"[ok, nothing, special, charge, diamond, member...","[ok, noth, special, charg, diamond, member, hi..."
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4* experience hotel monaco seat...,nice rooms not 4star experience hotel monaco s...,nice rooms not 4star experience hotel monaco s...,"[nice, rooms, not, 4star, experience, hotel, m...","[nice, room, not, 4star, experi, hotel, monaco..."
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...",unique great stay wonderful time hotel monaco ...,"[unique, great, stay, wonderful, time, hotel, ...","[uniqu, great, stay, wonder, time, hotel, mona..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...",great stay great stay went seahawk game awesom...,"[great, stay, great, stay, went, seahawk, game...","[great, stay, great, stay, went, seahawk, game..."

In [ ]:
nltk.download('wordnet')
wdLem = WordNetLemmatizer()
data['Lemmatised'] = data['tokenised'].apply(lambda x : [wdLem.lemmatize(word) for word in x])
data['Lemmatised']

[nltk_data] Downloading package wordnet to /root/nltk_data...

0      [nice, hotel, expensive, parking, got, good, d...
1      [ok, nothing, special, charge, diamond, member...
2      [nice, room, not, 4star, experience, hotel, mo...
3      [unique, great, stay, wonderful, time, hotel, ...
4      [great, stay, great, stay, went, seahawk, game...
                             ...
104    [fairmont, hotel, singapore, splendid, stayed,...
105    [great, hotel, stayed, hotel, night, route, pe...
106    [great, hotel, centre, stayed, 5, night, room,...
107    [great, location, great, value, great, hotel, ...
108    [lovely, hotel, great, location, stayed, vacat...
Name: Lemmatised, Length: 109, dtype: object

In [ ]:
tokens_cleaned = sum(data['Lemmatised'],[])
unigrams = (pd.Series(nltk.ngrams(tokens_cleaned,1)))
bigrams = (pd.Series(nltk.ngrams(tokens_cleaned,2)))
bigrams.value_counts()

(great, location)     24
(space, needle)       21
(hotel, monaco)       16
(staff, friendly)     12
(great, view)         12
                      ..
(room, starting)       1
(changed, 3)           1
(warwick, changed)     1
(trip, 3)              1
(right, downtown)      1
Name: count, Length: 8263, dtype: int64